### PR TITLE
Filetype encoding

### PR DESCRIPTION
**Pull request by kippesp**
Please look over these two commits regarding now the files are encoded and line endings are handled in the repo.  The current repo settings make it challenging for branch merges and viewing diff representations.

These changes were made automatically by `git add` because of the .gitattributes file settings and by `dos2unix`.  No other text has been altered with this change.

### CODE REVIEW

**Comment by fdwr** [comment]
Oops, I got your email and similar made changes before before I even saw this notification. 😅

**Comment by fdwr** [comment]
I'd like to keep CR LF (yes, I'm biased), but my newly added `.gitattributes` isn't *that* different from yours, and I ensured there were no UTF-16 files remaining, making this PR now fairly moot? Thank you Paul.

**Comment by kippesp** [comment]
Not a problem with making all the changes directly.  But the line endings are presenting me with some difficulty, even on Windows with git-for-windows installed from VS2022.

The adjustment you made to .gitattributes should be fine.  Let the value float--so a default git-for-windows will (eventually) work properly.  That said, there are inconsistencies among the files.  You can see the situation with this output from Windows, no .gitconfig changes:

```bash
$ git ls-files --eol
i/crlf  w/crlf  attr/-text              .gitattributes
i/crlf  w/crlf  attr/-text              .gitignore
i/lf    w/crlf  attr/text               BiNums.cpp
i/-text w/-text attr/-text              BiNums.png
i/crlf  w/crlf  attr/text eol=crlf      BiNums.sln
i/lf    w/crlf  attr/text eol=crlf      BiNums.vcxproj
i/lf    w/crlf  attr/text               FixedNumber.h
i/crlf  w/crlf  attr/text               Float16m7e8s1.h
i/crlf  w/crlf  attr/text               Half.h
i/crlf  w/crlf  attr/text               Int24.h
i/crlf  w/crlf  attr/text               Readme.md
i/lf    w/crlf  attr/text               precomp.cpp
i/lf    w/crlf  attr/text               precomp.h
```

The left column is the repos line endings.  Column two is my local line endings.  Any file where the *repo* file is CRLF is causing me fits.  I have my guesses, but that is besides the point.  Having an EOL "difference" is the issue.

Can you run `git add --renormalize .` on your repo from a regular DOS prompt--git should be in the path--and commit push that change?  After a renormalization, all the project code files should show LF as the repo format and CRLF as the local format.  Here's what I see and you should too--barring some global override:

```bash
$ git commit -m 'renormalize'
[master 745610e] renormalize
 5 files changed, 3380 insertions(+), 3380 deletions(-)

kippesp@luna MINGW64 ~/projects/seebinums.git (master|u+1 origin/master)
$ git ls-files --eol
i/crlf  w/crlf  attr/-text              .gitattributes
i/crlf  w/crlf  attr/-text              .gitignore
i/lf    w/crlf  attr/text               BiNums.cpp
i/-text w/-text attr/-text              BiNums.png
i/lf    w/crlf  attr/text eol=crlf      BiNums.sln
i/lf    w/crlf  attr/text eol=crlf      BiNums.vcxproj
i/lf    w/crlf  attr/text               FixedNumber.h
i/lf    w/crlf  attr/text               Float16m7e8s1.h
i/lf    w/crlf  attr/text               Half.h
i/lf    w/crlf  attr/text               Int24.h
i/lf    w/crlf  attr/text               Readme.md
i/lf    w/crlf  attr/text               precomp.cpp
i/lf    w/crlf  attr/text               precomp.h
```

**Comment by fdwr** [comment]
> Having an EOL "difference" is the issue.

I normalized them so that all files now consistently show the same line break type for index and working tree (perhaps the opposite *direction* that you wanted though :b), and I disabled automagic normalization (most good text editors follow the existing line feed style of the file opened anyway, like VS, VS Code, TedNPad...) while still enabling them as diffable, meaning that any file hashes computed on the source files should yield the same value regardless of OS. I wonder if the "fits" you mention still happen now, and whether the issue was in your text editor or with git?

```
D:\src\BiNums > git ls-files --eol
i/crlf  w/crlf  attr/-text              .gitattributes
i/crlf  w/crlf  attr/-text              .gitignore
i/crlf  w/crlf  attr/-text              BiNums.cpp
i/-text w/-text attr/-text              BiNums.png
i/crlf  w/crlf  attr/-text              BiNums.sln
i/crlf  w/crlf  attr/-text              BiNums.vcxproj
i/crlf  w/crlf  attr/-text              FixedNumber.h
i/crlf  w/crlf  attr/-text              Float16m7e8s1.h
i/crlf  w/crlf  attr/-text              Half.h
i/crlf  w/crlf  attr/-text              Int24.h
i/crlf  w/crlf  attr/-text              Readme.md
i/crlf  w/crlf  attr/-text              precomp.cpp
i/crlf  w/crlf  attr/-text              precomp.h
```

Sanity test shows diffs still work. e.g. https://github.com/fdwr/BiNums/commit/a37f54bae1a1188b5c37e1de0b15528b289375e0

**Pull request closed without merging**
